### PR TITLE
feature: autoScalerController implementation

### PR DESCRIPTION
**Pull request by dipankardas011**
# Tasks description

This PR will add all the design decisions here
and all the implementations related to it will be done on `ksctl/ksctl/main/ksctl-components` folder

### Related Issue(s)
- https://github.com/ksctl/ksctl/issues/289
- https://github.com/ksctl/ksctl/issues/251

# Solution

### Sub-Tasks
- [ ] https://github.com/ksctl/ksctl/pull/304

# Note to reviewers

- [ ] Ran Tests locally
- [ ] Checked [Contribution's guidelines](https://docs.ksctl.com/docs/contribution-guidelines/)

### CODE REVIEW

**Comment by dipankardas011** [comment]
> [!Note]
> date: 9-3-2024

image

**Comment by dipankardas011** [comment]
## Updates

- I have updated the location of the idea.md to seperate and new document
- also added a design document which needs to be reviewed!

**Comment by dipankardas011** [comment]
Also I am replacing this PR #301 in ksctl/ksctl to a new PR so that we can use the ksctl branch instead of folk

**Comment by dipankardas011** [comment]
also do add a note or warning that we should not use a api key of user instead a restricted apikey just for security reasons

**Comment by dipankardas011** [comment]
Should we make the ksctl agent to do k8s client call to fetch the configmap or we can tell the controller 2 for geting the data from the configmap and create a grpc call to the ksctl agent

But I am worrying about that controller has to wait for the response of the ksctl agent when using the second method

and if we are having the agent to use configmap then whenever it completes it can update the info

what do you say about that

**Comment by dipankardas011** [comment]
> ## Question ❓
> Should we make the ksctl agent to do k8s client call to fetch the configmap or we can tell the controller 2 for geting the data from the configmap and create a grpc call to the ksctl agent
> 
> But I am worrying about that controller has to wait for the response of the ksctl agent when using the second method
> 
> and if we are having the agent to use configmap then whenever it completes it can update the info
> 
> what do you say about that

currently I have implemented this method of operation for ksctl agent
the ksctl agent will be a deployment with serviceAccount which has all RBAC access for configmaps for it to fetch the state of the ksctl and write as well and the tokens for cloud provider will be passed by  the environment variable same goes for the storage driver

> [!Note] by this controller 2 only has to tell the ksctl agent what is the desired workernodes and it will attach and write that back to the state.json configmap
this making the roles of the ksctlagent clearnly seperatble

**Comment by dipankardas011** [comment]
https://github.com/ksctl/ksctl/pull/304

**Comment by Horiodino** [comment]
> > ## Question ❓
> > Should we make the ksctl agent to do k8s client call to fetch the configmap or we can tell the controller 2 for geting the data from the configmap and create a grpc call to the ksctl agent
> > But I am worrying about that controller has to wait for the response of the ksctl agent when using the second method
> > and if we are having the agent to use configmap then whenever it completes it can update the info
> > what do you say about that
> 
> currently I have implemented this method of operation for ksctl agent the ksctl agent will be a deployment with serviceAccount which has all RBAC access for configmaps for it to fetch the state of the ksctl and write as well and the tokens for cloud provider will be passed by the environment variable same goes for the storage driver
> 
> Note
> 
> by this controller 2 only has to tell the ksctl agent what is the desired workernodes and it will attach and write that back to the state.json configmap this making the roles of the ksctlagent clearnly seperatble

the first option is more reliable as the agent is doing all the work, ksctl agent can autonomously manage its own configuration data!

**Comment by dipankardas011** [comment]
Thanks everyone @Horiodino @prateek041 I am merging this PR

**Pull request merged**
